= Meecrowave Sample

This project shows how to use https://openwebbeans.apache.org/meecrowave/[Apache Meecrowave] for simple applications.

== About Apache Meecrowave

Apache Meecrowave is a 9 MByte small embeddable Java Application Server based on the following Apache JavaEE 8 projects:

* Apache Tomcat-9.x
* Apache log4j2
* Apache OpenWebBeans-2.x
* Apache Johnzon-1.1.x
* Apache CXF-3.x


== About our Examples

Here's what it provides:

0. A pom.xml with the dependencies for this sample and meecrowave-maven-plugin setup so you can launch `mvn package meecrowave-run`.
1. A sample JAX-RS application: in src/main/java/com/superbiz/sample/jaxrs
2. A test using JAX-RS client API and the meecrowave mono rule (useful when you run multiple tests) in src/test/java/com/superbiz/sample/jaxrs
3. in src/main/java/com/superbiz/configuration/Defaults some enrichment of the meecrowave Cli options for the application.

To use it launch meecrowave main (org.apache.meecrowave.runner.Cli) with option `--app-default-name foo`.

== Further Resources

=== Bug Reporting
Please use our official https://issues.apache.org/jira/projects/MEECROWAVE[Meecrowave Bug Tracker] for reporting bugs or enhancement requests.

=== Apache Meecrowave resources

Please find more information about Meecrowave on our https://openwebbeans.apache.org/meecrowave/[Apache Meecrowave Project Site]
